Sprint11
BegemotKotei/java-filmorate pull request #5
Opened 2023-02-08 14:50 UTC by BegemotKotei

сломал файл. Думаю из-за зав. скриптов и БД, пришлось всё по новой.

2023-02-08 16:44 UTC, andrew-larkin requested changes
Привет! Сам код и реализация достаточно качественны, все сделано в соответствии с требованиями. Одна небольшая правка и работа будет принята.

2023-02-08 16:44 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +
давай перенесем это в exception

2023-02-08 16:44 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +import ru.yandex.practicum.filmorate.exception.InternalException;
давай перенесем это в exception

2023-02-09 03:12 UTC, BegemotKotei commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHandler.java
> +package ru.yandex.practicum.filmorate.exception;
Перенёс

2023-02-09 03:12 UTC, BegemotKotei commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorResponse.java
> +package ru.yandex.practicum.filmorate.exception;
Перенёс

2023-02-11 10:53 UTC, merged